services:
  samba_server:
    # build: .
    image: jairf/samba_server:0.2
    tty: true # make container run in background
    restart: unless-stopped
    # network_mode: "host"
    ports:
      - "139:139"
      - "445:445"
      #- "80:80"
      #- "22:22"
    volumes:
      - ${PWD}/data/sambaUsers.back:/server_scripts/sambaUsers.back
      - /media/server/Samba_Share:/media/Data/Samba_Share_Device/Samba_Share
