services:
  samba_server:
    # build: .
    image: jairf/samba_server:2.0.1
    tty: true # make container run in background
    restart: unless-stopped
    # network_mode: "host"
    ports:
      - "139:139"
      - "445:445"
      - "80:80"
    volumes:
      - /media/server/Samba_Share:/samba_server/data
