services:
  samba_server:
    # build: .
    image: jairf/samba_server:0.2
    tty: true # make container run in background
    restart: unless-stopped
    # network_mode: "host"
    ports:
      - "139:139"
      - "445:445"
      #- "80:80"
      #- "22:22"
    volumes:
      #- ${PWD}/data/user_creds.bak:/server_scripts/user_creds.bak
      - /media/server/Samba_Share:/samba_server/data
