name: Build + Publish

on: push

jobs:
  build-push-container:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Update system
        run: sudo apt update && sudo apt upgrade -y
      - name: Install shellcheck
        run: sudo apt install -y shellcheck
      - name: Shell Linting
        run: shellcheck scripts/*.sh .devcontainer/*.sh

# recursive shellcheck    
# find . -type f -exec grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; | xargs shellcheck